apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "aquiladb-hpa"
  namespace: "default"
  labels:
    app: "aquiladb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "aquiladb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
