apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aquiladb
spec:
  selector:
    matchLabels:
      app: aquiladb
  serviceName: aquiladb
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aquiladb
    spec:
      containers:
        - name: aquiladb
          image: gcr.io/plexus-1d216/github.com/peterdeepsix/aquiladb@sha256:38e2804ec46237697a70bde5a193f61ec619655bfc358abe5b310b7893f4386d
          ports:
            - containerPort: 50051
              name: aquiladb
          volumeMounts:
            - name: aquiladb-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: aquiladb-data
        annotations:
          volume.beta.kubernetes.io/storage-class: fast
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
